### ISSUE TITLE
Command-Return to post comment

### ISSUE THREAD

**Issue by jamiewilson** [weld-co/welderwire-theme#19]
_From @austinmann on March 19, 2015 0:43_

I always really appreciate it when I can complete a form w/ keyboard shortcut. 

Like to "Add Comment" on a conversation thread it would be awesome. (similar to what you did on the FormKeep stuff.) 

_Copied from original issue: weld-co/telescope-theme-weld#39_

**Comment by jamiewilson** [comment]
_From @austinmann on March 19, 2015 0:43_

and exactly like what GitHub does, to post this very comment :-)

**Comment by jamiewilson** [comment]
_From @austinmann on May 5, 2015 15:52_

is this possible? 

I still try to Command-Return every time I post a comment :-)

**Comment by jamiewilson** [comment]
Looks like someone has added this for the next release: https://trello.com/c/t3I4E50s/74-keyboard-shortcuts

**Comment by jamiewilson** [comment]
_From @austinmann on May 13, 2015 18:12_

awesome! pumped for it to come out :-)

**Comment by austinmann** [comment]
Yes! I just tried this and it worked! Pumped.
