### ISSUE TITLE
Sort by Newest Users

### ISSUE THREAD

**Issue by austinmann** [weld-co/welderwire-theme#33]
it would be great to make a feature where it's really easy to find the most recently added users to the WELDER Wire… 

this would make it really easy to find out who "that new member" around the space is that you can't remember their name or haven't met.

**Comment by jamiewilson** [comment]
Good idea. Done.

![screen shot 2015-06-30 at 9 59 24 am](https://cloud.githubusercontent.com/assets/3308673/8434043/bd85ef22-1f0e-11e5-992c-1ca10471a216.png)
