### ISSUE TITLE
Member Directory / Find WELDERs

### ISSUE THREAD

**Issue by austinmann** [weld-co/welderwire-theme#34]
what do you think about renaming the Member Directory in the side bar to something a little more personal like "People" or "Find WELDERs" 

I think I like Find WELDERs best. 

people keeping coming up to me and asking questions like "is there any place where we can see the people around us and what they do? "  or "is there any place I can find out about all the WELDERs in Dallas?"   

it's like they aren't realizing what the Member Directory is.

**Comment by jamiewilson** [comment]
I happened to be doing similar task to this and need it to work for CCL anyway, so I went ahead and added this setting. 

![screen shot 2015-06-29 at 2 28 27 pm](https://cloud.githubusercontent.com/assets/3308673/8416434/602cf490-1e6b-11e5-8a12-e0b4ce4622e9.png)

**Comment by austinmann** [comment]
awesome!
