### ISSUE TITLE
How to add this theme to my Telescope app?

### ISSUE THREAD

**Issue by yizhiheng** [weld-co/welderwire-theme#36]
Is there any detailed setup instruction for welderwire-theme????😰

Can anyone help??

**Comment by jamiewilson** [comment]
Hey there. Just clone the repo into a `packages` directory within your telescope project. Then add it  to your `.meteor/packages` file:

```
############ Your Custom Packages ############
welderwire-theme
```

See the readme for other packages that this theme uses: https://github.com/weld-co/welderwire-theme/blob/master/README.md

**Comment by yizhiheng** [comment]
Thank you so much for your reply! But I got another question...
My application is called ideas. I created the `packages` directory within `ideas` project just like the img below.
<img width="600" alt="screen shot 2015-07-28 at 4 43 32 pm" src="https://cloud.githubusercontent.com/assets/3829080/8943240/cf230e28-3547-11e5-9e29-174dd355a27e.png">
And my packages file is like this...
<img width="1035" alt="screen shot 2015-07-28 at 4 48 10 pm" src="https://cloud.githubusercontent.com/assets/3829080/8943349/7f9c98aa-3548-11e5-89f4-8f9662fc4e66.png">
I run the app and everything seems good.
<img width="439" alt="screen shot 2015-07-28 at 4 49 22 pm" src="https://cloud.githubusercontent.com/assets/3829080/8943387/ca86e9ce-3548-11e5-9b12-2140c4e874ed.png">
I tried to open the app in the browser. But I can only get an empty page😖
<img width="629" alt="screen shot 2015-07-28 at 4 52 06 pm" src="https://cloud.githubusercontent.com/assets/3829080/8943447/ff3779b8-3548-11e5-8a09-d5f9fab66454.png">
Did I miss something??? Any idea how to fix this??? Very thankful for your help!😉

**Comment by jamiewilson** [comment]
It sounds like you need to edit your `packages` file within your `.meteor` directory. 

![screen shot 2015-07-28 at 3 57 46 pm](https://cloud.githubusercontent.com/assets/3308673/8943663/7e109150-3541-11e5-8b01-8f79cc892302.png)

so i guess it would be `ideas/.meteor/packages`. Does that make sense?

**Comment by yizhiheng** [comment]
Actually my packages file is in the `ideas/.meteor` directory... 
<img width="719" alt="screen shot 2015-07-28 at 5 05 59 pm" src="https://cloud.githubusercontent.com/assets/3829080/8943851/f6c17f34-354a-11e5-983d-22a9f1fa041f.png">

**Comment by jamiewilson** [comment]
is your install of Telescope working without welderwire-theme? I'd check the devtools console for error messages.

**Comment by yizhiheng** [comment]
Yes.. If I remove this part,
<img width="423" alt="screen shot 2015-07-28 at 5 12 33 pm" src="https://cloud.githubusercontent.com/assets/3829080/8943989/e040b86e-354b-11e5-951a-470111e6b7ff.png">
And it just magically works.
<img width="676" alt="screen shot 2015-07-28 at 5 13 36 pm" src="https://cloud.githubusercontent.com/assets/3829080/8944007/0aacdaf6-354c-11e5-914f-9812113ec434.png">

**Comment by jamiewilson** [comment]
Try this. comment out the base and hubble theme and then just add welderwire-theme:

```
…
telescope:tags
# telescope:theme-base
# telescope:theme-hubble
telescope:update-prompt

############ Your Custom Packages ############

welderwire-theme
```

**Comment by yizhiheng** [comment]
I did as you said, comment out the base and hubble theme and add welderwire-theme...
<img width="402" alt="screen shot 2015-07-28 at 7 17 23 pm" src="https://cloud.githubusercontent.com/assets/3829080/8946371/87ceb2b4-355d-11e5-86fe-b3af633e2954.png">
The app doesn't even run... I can see some crashing info at terminal like below.
<img width="711" alt="screen shot 2015-07-28 at 7 17 38 pm" src="https://cloud.githubusercontent.com/assets/3829080/8946385/c0958a64-355d-11e5-8007-935b1728e6c5.png">

If I do like this, the app runs..
<img width="376" alt="screen shot 2015-07-28 at 7 21 20 pm" src="https://cloud.githubusercontent.com/assets/3829080/8946400/e33c2fc8-355d-11e5-96ef-687e0e4a953a.png">
But still a empty page in browser...

If you have any telescope demo app which already integrated welderwire-theme, that would be great~

**Comment by jamiewilson** [comment]
what's your browser console say is happening?

**Comment by yizhiheng** [comment]
I guess it loaded all the js files but got nothing in `<body>`
<img width="1096" alt="screen shot 2015-07-28 at 7 40 58 pm" src="https://cloud.githubusercontent.com/assets/3829080/8946732/e0da219c-3560-11e5-806e-3286ca163a59.png">
<img width="1094" alt="screen shot 2015-07-28 at 7 41 05 pm" src="https://cloud.githubusercontent.com/assets/3829080/8946733/e0e9052c-3560-11e5-9af0-74bb817caf68.png">

**Comment by jamiewilson** [comment]
make sure your version of Telescope is up to date. run `meteor update` or `git pull` depending on how you have it installed. I think if you do that, and keep the base and hubble themes disabled, you can use my same packages config (as listed in the readme) to get it working.

**Comment by yizhiheng** [comment]
<img width="669" alt="screen shot 2015-07-28 at 7 50 24 pm" src="https://cloud.githubusercontent.com/assets/3829080/8946831/2f482aa8-3562-11e5-80da-2b02ad61fad3.png">
After I run this, magic happens.....
Thank you so much for helping out!!!!! 😃 Amazing theme you created!!  Sorry for the disturbing, I am just a telescope beginner...  I would like to buy you a coffee if i can...☕️

**Comment by jamiewilson** [comment]
No worries man. I've been there too :) Glad you got it up and running.
